language: bash

# Taken from: https://github.com/koalaman/shellcheck/issues/589

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - bash lint

matrix:
  fast_finish: true
