#!/usr/bin/env bash
#
# Check whether an oakthree variable exists.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR"/../oakthree.sh

tmux show-option -gv "@$OT_PREFIX-$1" > /dev/null 2>&1
