#!/usr/bin/env bash
#
# Create a new project given a path.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR"/../oakthree.sh

if [ -z "$1" ]; then
  exit
fi

directory=$(_tmux display-message -p '#{pane_current_path}')
window_name=$(basename "$directory")
shell_name="$window_name$OT_SHELL_SUFFIX"

# Probably have to refine this at some point. If the user tries to start a
# project in a directory with a basename identical to another project, the old
# project's windows are removed. Might want to add some method for allowing
# that in the future, but it's not high-priority right now.
_tmux remove-window "$OT_PROJECTS:$window_name"
_tmux remove-window "$OT_PROJECTS:$shell_name"

_tmux switch-client -t "$OT_PROJECTS" \; \
  new-window            \
    -c "$directory"     \
    -n "$shell_name"    \
    "$BIN_DIR/shell" \; \
  new-window            \
    -c "$directory"     \
    -n "$window_name"   \
    "$BIN_DIR/editor"
