#!/usr/bin/env bash
#
# Create a new project given a path.
# $1 - Absolute path which in which the project will start.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_DIR/../oakthree.sh

if [ -z "$1" ]; then
  exit
fi

directory="$1"
window_name=$(basename "$directory")
shell_name="$window_name$OT_SHELL_SUFFIX"

_tmux switch-client -t $OT_PROJECTS

_tmux remove-window "$window_name"
_tmux remove-window "$shell_name"

_tmux new-window -d \
  -c "$directory" \
  -n "$shell_name"

_tmux new-window \
  -c "'$directory'" \
  -n "$window_name" \
  "$BIN_DIR/editor"
